### ISSUE TITLE
Potential issue with DB architecture

### ISSUE THREAD

**Issue by Scifiler-sys** [220118-Reston-NET/Hyunsoo-Jeon-P0#1]
StoreFront isn't related to LineItem table at all. Instead, it is related to stores_products join table and you can put in the quantity column there instead

This is to avoid the issue that changing your store quantity will also change past orders quantity since they are connected.

Hint:

stores_products = Inventory model
orders_products = LineItem model

**Comment by hsprime85** [comment]
Thank you :)
